# steam:
#   username: "your_steam_username"
#   password: "your_steam_password"
# github_token: "your_default_github_token"
apps:
  #Team Fortress 2
  440:
    #branch:
    webhooks:
      - repo: "steamtracking/gametracking-tf2"
        #access_token:
        workflow_id: update.yml
        branch: master
  #Dota 2
  570:
    #branch:
    webhooks:
      - repo: "steamtracking/gametracking-dota2"
        #access_token:
        workflow_id: update.yml
        branch: master
  #CS2
  730:
    #branch:
    webhooks:
      - repo: "steamtracking/gametracking-cs2"
        #access_token:
        workflow_id: update.yml
        branch: master
  #SteamVR
  250820:
    branch: beta
    webhooks:
      - repo: "steamtracking/gametracking-steamvr"
        #access_token:
        workflow_id: update.yml
        branch: master
  1422450:
    #branch:
    webhooks:
      - repo: "steamtracking/gametracking-deadlock"
        #access_token:
        workflow_id: update.yml
        branch: master